### ISSUE TITLE
loss function mistake

### ISSUE THREAD

**Issue by Javdat** [BayerSe/esreg#9]
Hi, 

Shouldn't this line:

https://github.com/BayerSe/esreg/blob/d2d599a1464147e7d3fd32d52be94a26a2d3ea19/R/loss_functions.R#L18

Be:
```
loss <- ((r <= q) - alpha) * G1_q - (r <= q) * G1_r  + 
```

According to formula 2 of https://projecteuclid.org/euclid.ejs/1559872834

Difference being `-alpha` on `G1_q` but not `G1_r`. 

<img width="599" alt="image" src="https://github.com/BayerSe/esreg/assets/19429297/2dbf2894-ea91-4d02-9541-7203ef8e8a46">

**Comment by BayerSe** [comment]
Hi,

yes, that looks like a bug. Thanks for reporting it!
